
version: 2

models:
  - name: dim_symbols
    description: "Dimension table containing information about equity-symbols"
    columns:
      - name: symbol
        data_type: string
        description: "The stock symbol or the identifier of the security."

      - name: name_of_company
        data_type: string
        description: "The stock name of the security."

      - name: series
        data_type: string
        description: The series of the security, such as equity shares, debentures, etc. Values are EQ, BE, BL, BT, GC, IL and IQ."

      - name: date_of_listing
        data_type: string
        description: "The date on which the shares will be/was traded for the first time on an exchange"

      - name: paid_up_value
        data_type: int64
        description: "The amount of money a company has been paid from shareholders in exchange for shares of its stock"

      - name: face_value
        data_type: int64
        description: "The company's net worth at the price of the share on its first day on the stock market"

  - name: fact_equity
    description: "Fact table for daily equities bhav_copy data in NSE"
    columns:
      - name: equity_id
        data_type: string
        description: "Unique identifier"

      - name: symbol
        data_type: string
        description: "The stock symbol or the identifier of the security."

      - name: series
        data_type: string
        description: "The series of the security, such as equity shares, debentures, etc. Values are EQ, BE, BL, BT, GC, IL and IQ."

      - name: open
        data_type: float64
        description: "Price at which the security opened on the day of the report."

      - name: high
        data_type: float64
        description: "Highest traded price of the security during the day."

      - name: low
        data_type: float64
        description: "Lowest traded price of the security during the day."

      - name: close
        data_type: float64
        description: "Price at which the security was traded at the end of the market."

      - name: last
        data_type: float64
        description: "Price at which the security was traded at the last transaction before the close of the market."

      - name: prevclose
        data_type: float64
        description: "Closing price of the security on the previous trading day."

      - name: tottrdqty
        data_type: int64
        description: "The total quantity or number of shares traded during the day."

      - name: tottrdval
        data_type: float64
        description: "The total value of the shares traded, calculated as the product of the traded quantity and the last traded price."

      - name: timestamp
        data_type: timestamp
        description: "The date of the report."

      - name: totaltrades
        data_type: int64
        description: >
          The number of trades that were executed for the security during the day. 
          E.g. for a stock, Trade 1 has quantity = 100, Trade 2 quantity = 1000. TOTALTRADES = 2 and TOTTRDQTY = 1100

      - name: ma_50
        data_type: float64
        description: "50-day moving average"

      - name: ma_200
        data_type: float64
        description: "200-day moving average"

      - name: change_in_close_price
        data_type: float64
        description: "Difference between a symbol's closing price on a trading day and its closing price on the previous trading day"

      - name: pct_change_in_close_price
        data_type: float64
        description: "Percentage difference between a security's closing price on a trading day and its closing price on the previous trading day"

      - name: instrument_type
        data_type: string
        description: "Type of the instrument. Currently all data is of type (Equity)"

      - name: name_of_company
        data_type: string
        description: "The stock name of the security"

      - name: date_of_listing
        data_type: string
        description: "The date on which the shares will be/was traded for the first time on an exchange"

      - name: face_value
        data_type: int64
        description: "The company's net worth at the price of the share on its first day on the stock market"
